ALTER TABLE  appointments ADD FOREIGN KEY (UserId) REFERENCES users (id)
ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE  appointments ADD FOREIGN KEY (DateId) REFERENCES users (id)
ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tokens ADD FOREIGN KEY (UserId) REFERENCES users (id)
ON DELETE CASCADE ON UPDATE CASCADE;